### ISSUE TITLE
not leaving game

### ISSUE THREAD

**Issue by Rikiez** [SkyHeroes/CSMC#1]
I have tried running this on my server however there is no way to leave a game even if u switch worlds it still shows the scoreboard and the guns is there way to fix?

**Comment by barpec12** [comment]
From what I know, @ricsal1 is working on it

**Comment by ricsal1** [comment]
Lo there,
Yes, I am working on it and there is a current Beta that should meet your requirements.
In future you will not get exactly this functionality because the world management I made with a private plugin that controls some permissions on CSMC, but what you need now is there.

Feel free to test it with your buddies at **csmc.mooo.com:25599**
The more you test it, and the more people comment it, the better it will get.

https://discord.gg/r6pxMdG4 to join our discord server

Regards

**Comment by MerkXD** [comment]
@ricsal1 can I get a new link to discord server?

**Comment by ricsal1** [comment]
> 
> 
> @ricsal1 can I get a new link to discord server?

https://discord.gg/tSXpBRfh

cheers

**Comment by ricsal1** [comment]
> @ricsal1 can I get a new link to discord server?

Permanent link

https://discord.gg/ubVkqBvyQw

**Comment by ricsal1** [comment]
should be working on latest version.
Closing issue, report new one with latest version if you find issues plz
